title: Michal Musialik
email: michal@michalmusialik.com
description: >
  Writing about code.
baseurl: ""
url: "https://michalmusialik.com"
github_username: musialik

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /:title
